### ISSUE TITLE
Docker Building Problems

### ISSUE THREAD

**Issue by captain-joni** [dwilhelm89/Ethermap#11]
I was trying to host my own ethermap instace as a docker Container via docker-compose, because this is an absolute cool Projekt. 
Sadly i coulnt get it to Work. 
First of al i had to replace the dockerfile/nodejs-bower-grunt with digitallyseamless/nodejs-bower-grunt, otherwise it wouldnt even start to build the container.
This is my Error Log:

```
Building ethermap
Step 1/13 : FROM digitallyseamless/nodejs-bower-grunt
 ---> 54852479d9a3
Step 2/13 : WORKDIR /app
 ---> Using cache
 ---> 2000c421f061
Step 3/13 : ADD package.json /app/
 ---> 432f4c51efa9
Step 4/13 : RUN npm install
 ---> Running in 83388003e2ec
npm WARN notice [SECURITY] grunt has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=grunt - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead
npm WARN notice [SECURITY] lodash has the following vulnerabilities: 1 critical, 3 high, 2 moderate, 1 low. Go here for more details: https://github.com/advisories?query=lodash - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] ejs has the following vulnerabilities: 1 critical, 1 high, 1 moderate. Go here for more details: https://github.com/advisories?query=ejs - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
npm WARN notice [SECURITY] socket.io has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=socket.io - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] karma has the following vulnerabilities: 2 moderate. Go here for more details: https://github.com/advisories?query=karma - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] express has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=express - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated raven@0.6.3: Please upgrade to @sentry/node. See the migration guide https://bit.ly/3ybOlo7
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN notice [SECURITY] lodash has the following vulnerabilities: 1 critical, 3 high, 2 moderate, 1 low. Go here for more details: https://github.com/advisories?query=lodash - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] underscore.string has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=underscore.string - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=minimatch - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN notice [SECURITY] getobject has the following vulnerability: 1 critical. Go here for more details: https://github.com/advisories?query=getobject - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] js-yaml has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://github.com/advisories?query=js-yaml - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] clean-css has the following vulnerability: 1 low. Go here for more details: https://github.com/advisories?query=clean-css - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated coffee-script@1.6.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN notice [SECURITY] bower has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=bower - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated bower@0.9.2: This Bower version has SECURITY BUG THAT ALLOWS TO WRITE TO ARBITRARY FILE ON YOUR COMPUTER when you install malicious package. Please upgrade Bower to at least version 1.8.8 if you don't want to get hacked. More info: https://snyk.io/blog/severe-security-vulnerability-in-bowers-zip-archive-extraction/
npm WARN deprecated svgo@0.3.7: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN notice [SECURITY] uglify-js has the following vulnerability: 1 low. Go here for more details: https://github.com/advisories?query=uglify-js - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] lodash has the following vulnerabilities: 4 high, 2 low. Go here for more details: https://github.com/advisories?query=lodash - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated ngmin@0.4.1: use ng-annotate instead
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN notice [SECURITY] tar has the following vulnerabilities: 7 high. Go here for more details: https://github.com/advisories?query=tar - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated tar@0.1.20: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://github.com/advisories?query=debug - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated coffee-script@1.7.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated mocha@1.12.1: Mocha v1.x is no longer supported.
npm WARN notice [SECURITY] request has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=request - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated request@2.26.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN notice [SECURITY] send has the following vulnerabilities: 1 moderate, 1 low. Go here for more details: https://github.com/advisories?query=send - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated connect@2.12.0: connect 2.x series is deprecated
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://github.com/advisories?query=debug - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] fresh has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=fresh - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN notice [SECURITY] cookie-signature has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=cookie-signature - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] underscore has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=underscore - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] http-proxy has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=http-proxy - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated chokidar@0.8.4: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN notice [SECURITY] lodash has the following vulnerabilities: 1 critical, 3 high, 2 moderate, 1 low. Go here for more details: https://github.com/advisories?query=lodash - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated connect@2.8.8: connect 2.x series is deprecated
npm WARN notice [SECURITY] useragent has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=useragent - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] log4js has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=log4js - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] mime has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=mime - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated log4js@0.6.38: 0.x is no longer supported. Please upgrade to 6.x or higher.
npm WARN notice [SECURITY] underscore.string has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=underscore.string - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN notice [SECURITY] lodash has the following vulnerabilities: 1 critical, 3 high, 2 moderate, 1 low. Go here for more details: https://github.com/advisories?query=lodash - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] qs has the following vulnerabilities: 3 high. Go here for more details: https://github.com/advisories?query=qs - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] underscore has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=underscore - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] shelljs has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://github.com/advisories?query=shelljs - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=minimatch - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN notice [SECURITY] cli has the following vulnerability: 1 low. Go here for more details: https://github.com/advisories?query=cli - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] request has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=request - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] fstream has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=fstream - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN notice [SECURITY] semver has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=semver - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] request has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=request - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated request@2.42.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.11.4: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN notice [SECURITY] semver has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=semver - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimist has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=minimist - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] growl has the following vulnerability: 1 critical. Go here for more details: https://github.com/advisories?query=growl - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] diff has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=diff - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] request has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=request - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated request@2.67.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN notice [SECURITY] qs has the following vulnerabilities: 3 high. Go here for more details: https://github.com/advisories?query=qs - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] tunnel-agent has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=tunnel-agent - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hawk has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=hawk - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated hawk@1.0.0: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN notice [SECURITY] uglify-js has the following vulnerabilities: 1 critical, 1 high. Go here for more details: https://github.com/advisories?query=uglify-js - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] negotiator has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=negotiator - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] xmlhttprequest has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=xmlhttprequest - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN notice [SECURITY] marked has the following vulnerabilities: 5 high, 3 moderate. Go here for more details: https://github.com/advisories?query=marked - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] underscore has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=underscore - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated wrench@1.3.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN notice [SECURITY] ws has the following vulnerabilities: 2 high, 1 low. Go here for more details: https://github.com/advisories?query=ws - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] qs has the following vulnerabilities: 3 high. Go here for more details: https://github.com/advisories?query=qs - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=minimatch - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.1.14: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN notice [SECURITY] semver has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=semver - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN notice [SECURITY] qs has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=qs - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] tunnel-agent has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=tunnel-agent - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] bl has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=bl - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hawk has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=hawk - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated formidable@1.0.14: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated hawk@1.1.1: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN notice [SECURITY] moment has the following vulnerabilities: 2 high, 1 moderate. Go here for more details: https://github.com/advisories?query=moment - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] bl has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=bl - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] qs has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=qs - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hawk has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=hawk - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN notice [SECURITY] tough-cookie has the following vulnerabilities: 1 high, 1 moderate. Go here for more details: https://github.com/advisories?query=tough-cookie - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated har-validator@2.0.6: this library is no longer supported
npm WARN deprecated mkdirp@0.5.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN notice [SECURITY] cryptiles has the following vulnerability: 1 critical. Go here for more details: https://github.com/advisories?query=cryptiles - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated cryptiles@0.2.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated mkdirp@0.3.0: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated sntp@0.2.4: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN notice [SECURITY] concat-stream has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=concat-stream - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] minimatch has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=minimatch - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated minimatch@0.0.5: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=hoek - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated hoek@0.9.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN notice [SECURITY] cli has the following vulnerability: 1 low. Go here for more details: https://github.com/advisories?query=cli - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] ini has the following vulnerability: 1 high. Go here for more details: https://github.com/advisories?query=ini - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated ini@1.0.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN notice [SECURITY] mout has the following vulnerabilities: 2 high. Go here for more details: https://github.com/advisories?query=mout - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated boom@0.4.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@2.0.3: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN notice [SECURITY] decompress has the following vulnerability: 1 critical. Go here for more details: https://github.com/advisories?query=decompress - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated uuid@1.4.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN notice [SECURITY] cryptiles has the following vulnerability: 1 critical. Go here for more details: https://github.com/advisories?query=cryptiles - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=hoek - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN notice [SECURITY] minimist has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=minimist - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN notice [SECURITY] got has the following vulnerability: 1 moderate. Go here for more details: https://github.com/advisories?query=got - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> ws@0.4.32 install /app/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/app/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:97: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/app/node_modules/ws/build'

> phantomjs@1.9.20 install /app/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-linux-x86_64.tar.bz2
Saving to /app/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2
Receiving...

Received 12854K total.
Extracting tar contents (via spawned process)
Removing /app/node_modules/phantomjs/lib/phantom
Copying extracted folder /app/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-linux-x86_64.tar.bz2-extract-1664387729605/phantomjs-1.9.8-linux-x86_64 -> /app/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /app/node_modules/phantomjs/lib/phantom/bin/phantomjs

> jpegtran-bin@0.2.0 postinstall /app/node_modules/jpegtran-bin
> node pre-build.js
  (node:198) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.

  3 passing (229ms)

pre-build test passed successfully, skipping build...

> gifsicle@0.1.7 postinstall /app/node_modules/gifsicle
> node index.js

path.js:39
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'path', 'string');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.basename (path.js:1300:5)
    at /app/node_modules/download/index.js:35:43
    at each (/app/node_modules/each-async/each-async.js:63:4)
    at module.exports (/app/node_modules/download/index.js:33:5)
    at /app/node_modules/bin-wrapper/index.js:108:20
    at /app/node_modules/bin-wrapper/index.js:141:24
    at /app/node_modules/bin-check/index.js:30:20
    at /app/node_modules/executable/index.js:39:20
    at FSReqWrap.oncomplete (fs.js:170:21)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@github:pipobscure/fsevents#7dcdf9fa3f8956610fd6f69f72c67bace2de7138 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@0.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN CollaborativeMap@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@0.1.7 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@0.1.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-28T17_55_34_220Z-debug.log
ERROR: Service 'ethermap' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1

```
The Only Important Stuff is at the End of course. 

Kind Regards Joni

**Comment by noerw** [comment]
I patched the docker issues in this fork: https://github.com/sitcomlab/Ethermap
It's not exactly actively maintained, but there is a deployment at WWU using this, so that fork is more maintained than this repo I think ;)

**Comment by captain-joni** [comment]
Thanks, now at least the Docker Build works.
But as soon as i update the grunt locally a rebuild is again not possible ( same error: The command '/bin/sh -c npm install' returned a non-zero code: 1)
And not updating the grunt works fine, bit i have the problem that now the DB doesnt seem to work properly?
```

ethermap_1  | GET /partials/main 200 0.897 ms - 371
ethermap_1  | GET /partials/toolbox 200 1.260 ms - 2837
ethermap_1  | GET /partials/chat 200 0.883 ms - 888
ethermap_1  | GET /partials/maphistory 200 0.997 ms - 1627
ethermap_1  | GET /partials/featureproperties 304 1.081 ms - -
ethermap_1  | GET /partials/tools 304 0.603 ms - -
ethermap_1  | GET /partials/featurehistory 200 0.795 ms - 2295
ethermap_1  | GET /presets/categories 200 0.382 ms - -
ethermap_1  | GET /presets/fields 200 0.388 ms - -
ethermap_1  | GET /presets/presets 200 0.224 ms - -
couchdb_1   | [notice] 2022-09-29T08:10:11.887877Z nonode@nohost <0.382.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
couchdb_1   | [error] 2022-09-29T08:10:11.888586Z nonode@nohost emulator -------- Error in process <0.11700.0> with exit value:
couchdb_1   | {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,400}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,375}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,404}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,97}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}
couchdb_1   |
couchdb_1   | [error] 2022-09-29T08:10:11.889049Z nonode@nohost emulator -------- Error in process <0.11700.0> with exit value:
couchdb_1   | {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,400}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,375}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,404}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,97}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}
couchdb_1   |
ethermap_1  | couldnt get DB: [object Object]
ethermap_1  | couldnt get DB: [object Object]
couchdb_1   | [notice] 2022-09-29T08:10:16.888554Z nonode@nohost <0.382.0> -------- chttpd_auth_cache changes listener died because the _users database does not exist. Create the database to silence this notice.
couchdb_1   | [error] 2022-09-29T08:10:16.888970Z nonode@nohost emulator -------- Error in process <0.11733.0> with exit value:
couchdb_1   | {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,400}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,375}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,404}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,97}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,198}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,145}]}]}
couchdb_1   |
```

And when loading a map ( the web interface is reachable) the "loading gif" ( the 3 dots) never disappear...  
And markerd dont get saved etc. 

What could be the problem?
Thanks for answering btw!!!!!!

**Comment by noerw** [comment]
you need to initialize the database first, see https://docs.couchdb.org/en/stable/setup/single-node.html for instructions.
cool to see another instance of ethermap in the wild :)

**Comment by captain-joni** [comment]
Ah thanks, that worked. I had to configure my reverse proxy for the couchdb as well, so i could do the Setup. 
Now it workes perfectly THX.
