### ISSUE TITLE
Error: Missing at Request._callback

### ISSUE THREAD

**Issue by koofah** [dwilhelm89/Ethermap#7]
i am constantly getting the below error. I get this error at /api/documentRevisions/username/13434397  - 500m

> 200 2ms
GET /presets/presets 200 35ms
{ Error: missing
    at Request._callback (E:\WORKSPACE\SERVER\htdocs\server\Apps\Dev\gh_maps
\node_modules\nano\nano.js:319:39)
    at Request.self.callback (E:\WORKSPACE\SERVER\htdocs\server\Apps\Dev\gh_
maps\node_modules\nano\node_modules\request\request.js:122:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (E:\WORKSPACE\SERVER\htdocs\server\Apps\Dev\gh_ma
ps\node_modules\nano\node_modules\request\request.js:888:14)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (E:\WORKSPACE\SERVER\htdocs\server\Apps\D
ev\gh_maps\node_modules\nano\node_modules\request\request.js:839:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'Error',
  scope: 'couch',
  status_code: 404,
  'status-code': 404,
  request:
   { method: 'GET',
     headers:
      { 'content-type': 'application/json',
        accept: 'application/json' },
     uri: 'http://koofah:Koofah710498@localhost:5984/hughes/1492737459272271
20?revs_info=true',
     jar: false },
  headers:
   { 'cache-control': 'must-revalidate',
     connection: 'close',
     'content-type': 'application/json',
     date: 'Fri, 21 Apr 2017 01:18:48 GMT',
     'x-couch-request-id': '31a2c62012',
     'x-couchdb-body-time': '0',
     'status-code': 404,
     uri: 'http://koofah:Koofah710498@localhost:5984/hughes/1492737459272271
20?revs_info=true' },
  errid: 'non_200',
  error: 'not_found',
  reason: 'missing',
  description: 'missing',
  stacktrace:
   [ 'Error: missing',
     '    at Request._callback (E:\\WORKSPACE\\SERVER\\htdocs\\server\\Apps\
\Dev\\gh_maps\\node_modules\\nano\\nano.js:319:39)',
     '    at Request.self.callback (E:\\WORKSPACE\\SERVER\\htdocs\\server\\A
pps\\Dev\\gh_maps\\node_modules\\nano\\node_modules\\request\\request.js:122
:22)',
     '    at emitTwo (events.js:106:13)',
     '    at Request.emit (events.js:191:7)',
     '    at Request.<anonymous> (E:\\WORKSPACE\\SERVER\\htdocs\\server\\App
s\\Dev\\gh_maps\\node_modules\\nano\\node_modules\\request\\request.js:888:1
4)',
     '    at emitOne (events.js:101:20)',
     '    at Request.emit (events.js:188:7)',
     '    at IncomingMessage.<anonymous> (E:\\WORKSPACE\\SERVER\\htdocs\\ser
ver\\Apps\\Dev\\gh_maps\\node_modules\\nano\\node_modules\\request\\request.
js:839:12)',
     '    at emitNone (events.js:91:20)',
     '    at IncomingMessage.emit (events.js:185:7)',
     '    at endReadableNT (_stream_readable.js:974:12)',
     '    at _combinedTickCallback (internal/process/next_tick.js:80:11)',
     '    at process._tickCallback (internal/process/next_tick.js:104:9)' ]
}

**Comment by koofah** [comment]
Bug Solved was due to using external  socket.io.
